apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  AUTH_PORT: "8081"
  AUTH_GRPC_PORT: "50051"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: techip-auth:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
            - name: grpc
              containerPort: 50051
          envFrom:
            - configMapRef:
                name: auth-config
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: http
      port: 8081
      targetPort: http
    - name: grpc
      port: 50051
      targetPort: grpc
