apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tip2-pr16

resources:
  - namespace.yaml
  - postgres.yaml
  - auth.yaml
  - tasks-secret.yaml
  - tasks-configmap.yaml
  - tasks-deployment.yaml
  - tasks-service.yaml

configMapGenerator:
  - name: postgres-init
    files:
      - init.sql=postgres-init.sql

generatorOptions:
  disableNameSuffixHash: true
