package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"tip2/services/graphql/graph/generated"
	"tip2/services/graphql/graph/model"
	"tip2/services/graphql/internal/client/tasksclient"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	task, err := r.TasksClient.Create(ctx, tasksclient.CreateTaskInput{
		Title:       input.Title,
		Description: valueOrEmpty(input.Description),
		DueDate:     valueOrEmpty(input.DueDate),
	})
	if err != nil {
		return nil, err
	}

	return toGraphTask(task), nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model.UpdateTaskInput) (*model.Task, error) {
	task, err := r.TasksClient.Update(ctx, id, tasksclient.UpdateTaskInput{
		Title:       input.Title,
		Description: input.Description,
		DueDate:     input.DueDate,
		Done:        input.Done,
	})
	if err != nil {
		return nil, err
	}

	return toGraphTask(task), nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	return r.TasksClient.Delete(ctx, id)
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	tasks, err := r.TasksClient.List(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Task, 0, len(tasks))
	for _, task := range tasks {
		result = append(result, toGraphTask(task))
	}

	return result, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	task, err := r.TasksClient.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	if task == nil {
		return nil, nil
	}

	return toGraphTask(*task), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
